version: '3'
services:
   redis:
     image: redis:latest
     restart: "always"
     container_name: redis
     ports:
       - "6379:6379"
     volumes:
       - ./link_data/redis/redis.conf:/etc/redis/redis.conf
       - ./link_data/redis/data:/data
     command: redis-server /etc/redis/redis.conf
     privileged: true